# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Mod properties
archives.name=ECR

plugins.architectury_plugin=3.5+
plugins.architectury_loom=1.17-SNAPSHOT
plugins.mod_publish_plugin=1.1.0

libs.minecraft=26.3
libs.kotlin=2.4.20
libs.iris=1.11.6
libs.iris.neoforge=1.11.4
libs.iris.neoforge.mc=26.2

# Mod data
mod.id=escr
mod.name=Essential Craft: Reimagined
mod.version=1.0.0
mod.group=com.algorithmlx
mod.description=
mod.license=ARR
mod.platforms=fabric,neoforge
